version: '3.8'

services:
  productos:
    build:
      context: .
      dockerfile: catalogo-productos/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
    networks:
      - cotizador-network

  materiales:
    build:
      context: .
      dockerfile: catalogo-materiales/Dockerfile
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
    networks:
      - cotizador-network

  filtros:
    build:
      context: .
      dockerfile: catalogo-filtros/Dockerfile
    ports:
      - "8083:8083"
    environment:
      - PORT=8083
    networks:
      - cotizador-network

networks:
  cotizador-network:
    driver: bridge
