services:
  productos:
    build:
      context: ./catalogo-productos
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
    networks:
      cotizador-network:
        ipv4_address: 172.20.0.10
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  materiales:
    build:
      context: ./catalogo-materiales
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
    networks:
      cotizador-network:
        ipv4_address: 172.20.0.11
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  filtros:
    build:
      context: ./catalogo-filtros
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      - PORT=8083
    networks:
      cotizador-network:
        ipv4_address: 172.20.0.12
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  cotizador-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
