name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: https://your-production-url.com  # Update with your production URL
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test
      
    - name: Build
      run: npm run build
      
    - name: Deploy to production
      run: |
        # Add your production deployment commands here
        echo "🚀 Deploying to production..."
        # Example: npm run deploy:prod
